### ISSUE TITLE
@TestPaymentV2Bot inline mode does not return anything 

### ISSUE THREAD

**Issue by Mammad900** [Muaath5/MuaathBots#1]
## Describe the bug
When I type `@TestPaymentV2Bot payment`, it loads for a few seconds and returns no results

## To Reproduce
1. Start @TestPaymentV2Bot 
2. Send the command `/inline`
3. Click 'Try inline here first 😁' 
4. See bug

## Expected behavior
At least one invoice should be returned, like the one in the screenshot. 

## Screenshot
![Screenshot_2021-12-07-17-34-01-555_org telegram messenger web](https://user-images.githubusercontent.com/67197540/145045561-19949952-4c0a-489d-8b05-1ec8c1a5db56.jpg)

## Configuration
- **Telegram client:** Telegram Android 
- **Telegram version:** 8.3.0
- **Used bot:** @TestPaymentV2Bot 

### Additional context
The problem seems to be from the part that sends the response to Telegram servers.

**Comment by Muaath5** [comment]
@Mammad900 Thanks, Bot will be updated.

**Comment by Muaath5** [comment]
Thanks, It was fixed.

Try now.
